name: test
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: coolOrangeLabs/powerLoad
        token: ${{ secrets.SOURCE_REPO_TOKEN }}





    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        path: current-repo

    - name: Copy documentation to New Repository
      run: cp ${{ github.workspace }}/README.md ./current-repo/README.md
      working-directory: .

    - name: Commit docuemntation changes
      run: |
        git config user.name "Marco Mirandola"
        git config user.email "marco.mirandola@coolorange.com"
        git add .
        git commit -m "Update documentation"
        git push origin main
