name: test
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v4
      with:
        repository: coolOrangeLabs/powerLoad
        token: ${{ secrets.SOURCE_REPO_TOKEN }}
        path: source-repo




    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        path: target-repo

    - name: Copy documentation to New Repository
      run: cp ${{ github.workspace }}/source-repo/README.md ${{ github.workspace }}/target-repo/README.md
      working-directory: .

    - name: Commit docuemntation changes
      run: |
        git config user.name "Marco Mirandola"
        git config user.email "marco.mirandola@coolorange.com"
        git add .
        git commit -m "Update documentation"
        git push origin main
